/**
 * McpBridge — generated by mcp-anything for editor
 *
 * Drop this component into your app's root layout (e.g. app/layout.tsx):
 *
 *   import { McpBridge } from './McpBridge'
 *   // Inside your layout:
 *   <McpBridge />
 *
 * The component renders nothing. It connects to the MCP server's local
 * WebSocket bridge and relays Zustand store actions in real time.
 */

'use client'

import { useEffect } from 'react'
import { useInteractive } from '@pascal-app/core'
import { useScene } from '@pascal-app/core'
import { useCommandPalette } from '@pascal-app/editor'
import { useAudio } from '@pascal-app/editor'
import { useCommandRegistry } from '@pascal-app/editor'
import { useEditor } from '@pascal-app/editor'
import { usePaletteViewRegistry } from '@pascal-app/editor'
import { useUploadStore } from '@pascal-app/editor'
import { useViewer } from '@pascal-app/viewer'

// ---------------------------------------------------------------------------
// Store registry — maps MCP store names to Zustand getState() functions
// ---------------------------------------------------------------------------
const STORES: Record<string, () => Record<string, unknown>> = {
  interactive: () => useInteractive.getState() as Record<string, unknown>,
  scene: () => useScene.getState() as Record<string, unknown>,
  commandpalette: () => useCommandPalette.getState() as Record<string, unknown>,
  audio: () => useAudio.getState() as Record<string, unknown>,
  commandregistry: () => useCommandRegistry.getState() as Record<string, unknown>,
  editor: () => useEditor.getState() as Record<string, unknown>,
  paletteviewregistry: () => usePaletteViewRegistry.getState() as Record<string, unknown>,
  uploadstore: () => useUploadStore.getState() as Record<string, unknown>,
  viewer: () => useViewer.getState() as Record<string, unknown>,
}

const BRIDGE_PORT =
  typeof process !== 'undefined'
    ? (process.env.NEXT_PUBLIC_MCP_BRIDGE_PORT ?? '9001')
    : '9001'

export function McpBridge() {
  useEffect(() => {
    const url = `ws://localhost:${BRIDGE_PORT}`
    let ws: WebSocket | null = null
    let reconnectTimer: ReturnType<typeof setTimeout> | null = null
    let alive = true

    const connect = () => {
      if (!alive) return
      ws = new WebSocket(url)

      ws.onopen = () => {
        console.log('[McpBridge] Connected to MCP server at', url)
      }

      ws.onmessage = async (event: MessageEvent) => {
        let request: { id: string; store: string; action: string; args?: Record<string, unknown> }
        try {
          request = JSON.parse(event.data as string)
        } catch {
          console.error('[McpBridge] Received non-JSON message:', event.data)
          return
        }

        const { id, store, action, args = {} } = request

        const getState = STORES[store]
        if (!getState) {
          ws?.send(JSON.stringify({
            id,
            success: false,
            error: `Unknown store: "${store}". Available: ${Object.keys(STORES).join(', ')}`,
          }))
          return
        }

        const state = getState()
        const fn = state[action]

        if (typeof fn !== 'function') {
          ws?.send(JSON.stringify({
            id,
            success: false,
            error: `Unknown action: "${store}.${action}"`,
          }))
          return
        }

        try {
          const argValues = Object.values(args)
          await (fn as (...a: unknown[]) => unknown)(...argValues)

          // Return a snapshot of the store state after the action
          const updated = getState()
          ws?.send(JSON.stringify({ id, success: true, data: updated }))
        } catch (err: unknown) {
          const message = err instanceof Error ? err.message : String(err)
          ws?.send(JSON.stringify({ id, success: false, error: message }))
        }
      }

      ws.onclose = () => {
        if (!alive) return
        console.log('[McpBridge] Disconnected. Reconnecting in 3s...')
        reconnectTimer = setTimeout(connect, 3000)
      }

      ws.onerror = () => {
        // onclose fires after onerror — reconnect handled there
      }
    }

    connect()

    return () => {
      alive = false
      if (reconnectTimer) clearTimeout(reconnectTimer)
      ws?.close()
    }
  }, [])

  return null
}
